apiVersion: v1
kind: Service
metadata:
  name: {{ include "little-quest-mmf.fullname" . }}
  labels:
    {{- include "little-quest-mmf.labels" . | nindent 4 }}
  {{- with .Values.mmf.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.mmf.service.type }}
  ports:
  - name: grpc
    port: {{ .Values.mmf.service.port }}
    protocol: TCP
    appProtocol: grpc
    targetPort: grpc
  - name: http
    port: {{ .Values.mmf.port.metricsPort }}
    protocol: TCP
    appProtocol: http
    targetPort: {{ .Values.mmf.port.metricsPort }}
  selector:
    {{- include "little-quest-mmf.selectorLabels" . | nindent 4 }}
