{{- if .Values.mmf.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "little-quest-mmf.serviceAccountName" . }}
  labels:
    {{- include "little-quest-mmf.labels" . | nindent 4 }}
  {{- with .Values.mmf.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
