{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
  labels:
    {{- include "secrets-store-csi-driver-provider-gcp.labels" . | indent 4 }}
  name: {{ template "secrets-store-csi-driver-provider-gcp.serviceAccountName" . }}-rolebinding
  namespace: {{ template "secrets-store-csi-driver-provider-gcp.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "secrets-store-csi-driver-provider-gcp.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "secrets-store-csi-driver-provider-gcp.serviceAccountName" . }}
  namespace: {{ template "secrets-store-csi-driver-provider-gcp.namespace" . }}
{{- end -}}
