{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
  labels:
    {{- include "secrets-store-csi-driver-provider-gcp.labels" . | indent 4 }}
  name: {{ template "secrets-store-csi-driver-provider-gcp.serviceAccountName" . }}
  namespace: {{ template "secrets-store-csi-driver-provider-gcp.namespace" . }}
{{- end -}}
