apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: open-match-synchronizer
  namespace: open-match
spec:
  host: open-match-synchronizer.open-match.svc.cluster.local
  subsets:
  - name: long-connection
    labels:
      app: open-match
      component: synchronizer
      release: open-match
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 300s
      http:
        http2MaxRequests: 4000
        idleTimeout: 300s
