apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "little-quest.fullname" . }}-config 
  labels:
    {{- include "little-quest.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
