apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
