apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: little-quest-mmf
  namespace: corp-0
spec:
  host: little-quest-mmf.corp-0.svc.cluster.local
  subsets:
  - name: long-connection
    labels:
      app.kubernetes.io/name: little-quest-mmf
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 300s
      http:
        http2MaxRequests: 4000
        idleTimeout: 300s
