apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "little-quest-realtime.fullname" . }}-config
  labels:
    {{- include "little-quest-realtime.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
