apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: {{ include "little-quest-realtime.fullname" . }}
  labels:
    {{- include "little-quest-realtime.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if not .Values.realtime.autoscaling.enabled }}
  replicas: {{ .Values.realtime.replicaCount }}
  {{- end }}
  scheduling: {{ .Values.realtime.scheduling }}
  {{- with .Values.realtime.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.realtime.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "little-quest-realtime.labels" . | nindent 8 }}
    spec:
      ports:
      - name: default
        portPolicy: {{ .Values.realtime.portPolicy }}
        containerPort: {{ .Values.realtime.port.containerPort }}
        protocol: {{ .Values.realtime.port.protocol }}
      health:
        {{- if .Values.realtime.health.disabled }}
        disabled: {{ .Values.realtime.health.disabled }}
        {{- end }} 
        initialDelaySeconds: {{ .Values.realtime.health.initialDelaySeconds }}
        periodSeconds: {{ .Values.realtime.health.periodSeconds }}
        failureThreshold: {{ .Values.realtime.health.failureThreshold }}
      sdkServer:
        logLevel: {{ .Values.realtime.sdkServer.logLevel }}
        grpcPort: {{ .Values.realtime.sdkServer.grpcPort }}
        httpPort: {{ .Values.realtime.sdkServer.httpPort }}
      template:
        metadata:
          {{- with .Values.realtime.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "little-quest-realtime.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.realtime.image.repository }}:{{ .Values.realtime.image.tag | default .Chart.AppVersion }}"
            ports:
            - name: http
              containerPort: {{ .Values.realtime.port.metricsPort }}
              protocol: TCP
            env:
            - name: APP_ENV
              value: {{ .Values.env }}
            - name: SERVICE_NAME
              value: {{ .Values.realtime.serviceName }}
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.googleCloudProjectId }}
            - name: TCP_PORT
              value: "{{ .Values.realtime.port.containerPort }}"
            - name: HTTP_PORT
              value: "{{ .Values.realtime.port.metricsPort }}"
            - name: PASSTHROUGH
              value: "{{ .Values.realtime.port.passthrough }}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONTAINER_NAME
              value: {{ .Chart.Name }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE_NAME),k8s.container.name=$(CONTAINER_NAME)
            {{- with .Values.realtime.liveness }}
            livenessProbe:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.realtime.readiness }}
            readinessProbe:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.realtime.startup }}
            startupProbe:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            resources:
              {{- toYaml .Values.realtime.resources | nindent 14 }}
          {{- with .Values.realtime.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.realtime.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.realtime.tolerations }}
          tolerations:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          terminationGracePeriodSeconds: {{ .Values.realtime.terminationGracePeriodSeconds }}
