apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "little-quest-realtime.fullname" . }}-agones-sdk-access
  labels:
    {{- include "little-quest-realtime.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:{{ .Release.Namespace }}:{{ include "little-quest-realtime.fullname" . }}
