apiVersion: v1
kind: Service
metadata:
  name: {{ include "little-quest-realtime.fullname" . }}
  labels:
    {{- include "little-quest-realtime.labels" . | nindent 4 }}
  {{- with .Values.realtime.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.realtime.service.type }}
  ports:
    - port: {{ .Values.realtime.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "little-quest-realtime.selectorLabels" . | nindent 4 }}
