apiVersion: v1
kind: Service
metadata:
  name: {{ include "little-quest-realtime.fullname" . }}
  labels:
    {{- include "little-quest-realtime.labels" . | nindent 4 }}
  {{- with .Values.realtime.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.realtime.service.type }}
  ports:
  - name: http
    port: {{ .Values.realtime.service.port }}
    protocol: TCP
    appProtocol: http
    targetPort: http
  selector:
    agones.dev/role: gameserver
