apiVersion: cloud-build-notifiers/v1
kind: GoogleChatNotifier
metadata:
  name: cloud-build-googlechat-notifier
spec:
  notification:
    filter: build.status in [Build.Status.SUCCESS, Build.Status.FAILURE, Build.Status.TIMEOUT]
    delivery:
      webhookUrl:
        secretRef: webhook-url
  secrets:
  - name: webhook-url
    value: projects/kentaiso-330205/secrets/cloud_build_notifier_url/versions/latest
