apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: open-match-frontend
  namespace: open-match
spec:
  hosts:
  - open-match-frontend.open-match.svc.cluster.local
  http:
  - name: default
    route:
    - destination:
        host: open-match-frontend.open-match.svc.cluster.local
        port:
          number: 50504
        subset: default
