apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "little-quest-frontend.fullname" . }}
  labels:
    {{- include "little-quest-frontend.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "little-quest-frontend.selectorLabels" . | nindent 6 }}
  {{- with .Values.frontend.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "little-quest-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "little-quest-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "little-quest-frontend.fullname" . }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.frontend.port.containerPort }}
            protocol: TCP
          env:
          - name: APP_ENV
            value: {{ .Values.env | quote }}
          - name: SERVICE_NAME
            value: {{ .Values.frontend.serviceName | quote }}
          - name: HTTP_PORT
            value: {{ .Values.frontend.port.containerPort | quote }}
          - name: OPENMATCH_FRONTEND_SERVICE_ADDR
            value: {{ .Values.frontend.openMatch.frontendService.address | quote }}
          - name: GOOGLE_CLOUD_PROJECT
            value: {{ .Values.googleCloudProjectId | quote }}
          - name: OTEL_SAMPLING_RATE
            value: {{ .Values.frontend.cloudTrace.samplingRate | quote }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONTAINER_NAME
            value: {{ .Chart.Name }}
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE_NAME),k8s.container.name=$(CONTAINER_NAME)
          {{- with .Values.frontend.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.startup }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- with .Values.frontend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 6 }}
        labelSelector:
          matchLabels:
          {{- include "little-quest-frontend.selectorLabels" $ | nindent 12 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.frontend.terminationGracePeriodSeconds }}
      {{- with .Values.frontend.volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
