apiVersion: v1
kind: Service
metadata:
  name: {{ include "little-quest-frontend.fullname" . }}
  labels:
    {{- include "little-quest-frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if .Values.frontend.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.frontend.port.containerPort }}
    protocol: TCP
    appProtocol: http
    targetPort: {{ .Values.frontend.port.containerPort }}
    {{- if .Values.frontend.service.nodePort }}
    nodePort: {{ .Values.frontend.service.nodePort }}
    {{- end }}
  selector:
    {{- include "little-quest-frontend.selectorLabels" . | nindent 4 }}
