#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: failed-job-cleaner
#  namespace: kube-system
#---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: failed-job-cleaner
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: failed-job-cleaner
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: failed-job-cleaner
  apiGroup: rbac.authorization.k8s.io

