apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: {{ include "little-quest.fullname" . }}
  labels:
    {{- include "little-quest.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  scheduling: {{ .Values.scheduling }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    spec:
      ports:
      - name: default
        portPolicy: {{ .Values.portPolicy }}
        containerPort: {{ .Values.port.containerPort }}
        protocol: {{ .Values.port.protocol }}
      health:
        disabled: {{ .Values.health.disabled }}
        initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
        periodSeconds: {{ .Values.health.periodSeconds }}
        failureThreshold: {{ .Values.health.failureThreshold }}
      sdkServer:
        logLevel: {{ .Values.sdkServer.logLevel }}
        grpcPort: {{ .Values.sdkServer.grpcPort }}
        httpPort: {{ .Values.sdkServer.httpPort }}
      template:
        spec:
          serviceAccountName: {{ include "little-quest.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            env:
            - name: APP_ENV
              value: {{ .Values.env }}
            - name: SERVICE_NAME
              value: {{ .Values.serviceName }}
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.googleCloudProjectId }}
            - name: PORT
              value: "{{ .Values.port.containerPort }}"
            - name: PASSTHROUGH
              value: "{{ .Values.port.passthrough }}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONTAINER_NAME
              value: {{ .Chart.Name }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(NAMESPACE_NAME),k8s.container.name=$(CONTAINER_NAME)
            {{- with .Values.liveness }}
            livenessProbe:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.readiness }}
            readinessProbe:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.startup }}
            startupProbe:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
