{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: {{ include "little-quest.fullname" . }}
  labels:
    {{- include "little-quest.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  fleetName: {{ include "little-quest.fullname" . }}
  policy:
    type: {{ .Values.autoscaling.type }}
    buffer:
      bufferSize: {{ .Values.autoscaling.bufferSize }}
      minReplicas: {{ .Values.autoscaling.minReplicas }}
      maxReplicas: {{ .Values.autoscaling.maxReplicas }}
{{- end }}
