apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: agones
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: corp-0
        name: gke_kentaiso-330205_asia-northeast1_prod-corp-0
  template:
    metadata:
      name: "agones"
    spec:
      project: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=false
      source:
        chart: agones
        repoURL: https://agones.dev/chart/stable
        targetRevision: 1.35.0
        helm:
          releaseName: "agones"
          values: |
             agones:
               metrics:
                 stackdriverEnabled: true
                 stackdriverProjectID: "kentaiso-330205"
                 stackdriverLabels: ""
               serviceaccount:
                 allocator:
                   name: agones-allocator
                   annotations:
                     iam.gke.io/gcp-service-account: agones-allocator@kentaiso-330205.iam.gserviceaccount.com
                 controller:
                   name: agones-controller
                   annotations:
                     iam.gke.io/gcp-service-account: agones-controller@kentaiso-330205.iam.gserviceaccount.com
               controller:
                 resources:
                   requests:
                     cpu: 50m
                     memory: 256Mi
                 tolerations: []
                 affinity:
                   nodeAffinity:
                     preferredDuringSchedulingIgnoredDuringExecution:
                     - weight: 1
                       preference:
                         matchExpressions:
                           - key: agones.dev/agones-system
                             operator: Exists
                 replicas: 2
                 pdb:
                     minAvailable: 1
               extensions:
                 resources:
                   requests:
                     cpu: 50m
                     memory: 256Mi
                 tolerations: []
               ping:
                 install: false
               allocator:
                 pdb:
                   enabled: true
                   minAvailable: 1
                 resources:
                   requests:
                     cpu: 50m
                     memory: 256Mi
                 tolerations: []
                 affinity:
                   nodeAffinity:
                     preferredDuringSchedulingIgnoredDuringExecution:
                     - weight: 1
                       preference:
                         matchExpressions:
                           - key: agones.dev/agones-system
                             operator: Exists
                 replicas: 2
                 service:
                   name: agones-allocator
                   serviceType: ClusterIP
                   http:
                     appProtocol: http
                     port: 18080
                     targetPort: 18080
                   grpc:
                     appProtocol: grpc
                     port: 8443
                     targetPort: 8443
                 disableMTLS: true
                 disableTLS: true
             gameservers:
               namespaces:
               - corp-0
               minPort: 7000
               maxPort: 8000

      ignoreDifferences:
      - group: ""
        kind: Secret
        name: agones-cert
        namespace: agones-system
        jsonPointers:
        - /data
      - group: ""
        kind: Secret
        name: allocator-client-ca
        namespace: agones-system
        jsonPointers:
        - /data
      - group: ""
        kind: Secret
        name: allocator-tls
        namespace: agones-system
        jsonPointers:
        - /data
      - group: ""
        kind: Secret
        name: allocator-tls-ca
        namespace: agones-system
        jsonPointers:
        - /data
      - group: ""
        kind: Secret
        name: allocator-client.default
        namespace: corp-0
        jsonPointers:
        - /data
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        name: agones-mutation-webhook
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: agones-validation-webhook
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
      - group: apiregistration.k8s.io
        kind: APIService
        name: v1.allocation.agones.dev
        jsonPointers:
        - /spec/caBundle
      destination:
        name: "{{name}}"
        namespace: agones-system
