apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: agones
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: corp-0
  template:
    metadata:
      name: "agones"
    spec:
      project: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=false
        automated:
          prune: true
          selfHeal: true
      source:
        chart: agones
        repoURL: https://agones.dev/chart/stable
        targetRevision: 1.45.0
        helm:
          releaseName: "agones"
          values: |
             agones:
               metrics:
                 stackdriverEnabled: false
               serviceaccount:
                 allocator:
                   name: agones-allocator
                   annotations:
                     iam.gke.io/gcp-service-account: agones-allocator@prd-little-quest.iam.gserviceaccount.com
                 controller:
                   name: agones-controller
                   annotations:
                     iam.gke.io/gcp-service-account: agones-controller@prd-little-quest.iam.gserviceaccount.com
               controller:
                 resources:
                   requests:
                     cpu: 50m
                     memory: 126Mi
                   limits:
                     cpu: 50m
                     memory: 126Mi
                 annotations:
                   sidecar.istio.io/inject: "false"
                 tolerations: []
                 affinity:
                   podAntiAffinity:
                     preferredDuringSchedulingIgnoredDuringExecution:
                     - podAffinityTerm:
                         labelSelector:
                           matchExpressions:
                           - key: agones.dev/role
                             operator: In
                             values:
                             - controller
                         topologyKey: kubernetes.io/hostname
                       weight: 100
                 topologySpreadConstraints:
                 - maxSkew: 1
                   topologyKey: kubernetes.io/hostname
                   whenUnsatisfiable: ScheduleAnyway
                   labelSelector:
                     matchLabels:
                       agones.dev/role: controller
                 replicas: 2
                 pdb:
                     minAvailable: 1
               extensions:
                 resources:
                   requests:
                     cpu: 50m
                     memory: 126Mi
                   limits:
                     cpu: 50m
                     memory: 126Mi
                 annotations:
                   sidecar.istio.io/inject: "false"
                 tolerations: []
                 affinity:
                   podAntiAffinity:
                     preferredDuringSchedulingIgnoredDuringExecution:
                     - podAffinityTerm:
                         labelSelector:
                           matchExpressions:
                           - key: agones.dev/role
                             operator: In
                             values:
                             - extensions
                         topologyKey: kubernetes.io/hostname
                       weight: 100
                 topologySpreadConstraints:
                 - maxSkew: 1
                   topologyKey: kubernetes.io/hostname
                   whenUnsatisfiable: ScheduleAnyway
                   labelSelector:
                     matchLabels:
                       agones.dev/role: extensions
                 replicas: 2
                 pdb:
                   minAvailable: 1
               ping:
                 install: false
               allocator:
                 labels:
                   service.istio.io/canonical-name: agones-allocator
                 annotations:
                   proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
                 pdb:
                   enabled: true
                   minAvailable: 1
                 resources:
                   requests:
                     cpu: 50m
                     memory: 126Mi
                   limits:
                     cpu: 50m
                     memory: 126Mi
                 tolerations: []
                 affinity:
                   podAntiAffinity:
                     preferredDuringSchedulingIgnoredDuringExecution:
                     - podAffinityTerm:
                         labelSelector:
                           matchExpressions:
                           - key: multicluster.agones.dev/role
                             operator: In
                             values:
                             - allocator
                         topologyKey: kubernetes.io/hostname
                       weight: 100
                 topologySpreadConstraints:
                 - maxSkew: 1
                   topologyKey: kubernetes.io/hostname
                   whenUnsatisfiable: ScheduleAnyway
                   labelSelector:
                     matchLabels:
                       multicluster.agones.dev/role: allocator
                 replicas: 2
                 service:
                   name: agones-allocator
                   serviceType: ClusterIP
                   annotations: {}
                   http:
                     appProtocol: http
                     port: 18080
                     portName: http-web
                     targetPort: 18080
                   grpc:
                     appProtocol: grpc
                     port: 8443
                     portName: grpc
                     targetPort: 8443
                 disableMTLS: true
                 disableTLS: true
                 allocationBatchWaitTime: 100ms
             gameservers:
               namespaces:
               - corp-0
               minPort: 7000
               maxPort: 8000

      destination:
        name: "{{name}}"
        namespace: agones-system
