apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: app-0
        name: gke_kentaiso-330205_asia-northeast1_prod-app-0
      - cluster: corp-0
        name: gke_kentaiso-330205_asia-northeast1_prod-corp-0
      - cluster: misc-0
        name: gke_kentaiso-330205_asia-northeast1-a_prod-misc-0
  template:
    metadata:
      name: "{{cluster}}-kube-state-metrics"
    spec:
      project: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      source:
        chart: kube-state-metrics
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 5.15.2
        helm:
          releaseName: "{{cluster}}-kube-state-metrics"
          values: |
            extraArgs:
            - --metric-allowlist=kube_pod_info,kube_pod_container_resource_requests,kube_pod_container_resource_limits,kube_pod_container_status_restarts_total,kube_pod_status_reason,kube_pod_status_phase,kube_pod_container_status_running,kube_pod_container_status_waiting,kube_pod_container_status_terminated,kube_node_info,kube_node_status_allocatable,kube_node_status_capacity,kube_node_spec_unschedulable,kube_node_status_condition,kube_deployment_status_replicas,kube_deployment_status_replicas_updated,kube_deployment_status_replicas_unavailable,kube_statefulset_status_replicas,kube_statefulset_status_replicas_ready,kube_horizontalpodautoscaler_spec_max_replicas,kube_horizontalpodautoscaler_spec_min_replicas,kube_horizontalpodautoscaler_status_current_replicas,kube_job_status_succeeded,kube_job_status_active,kube_job_status_failed,kube_job_status_completion_time
      destination:
        name: "{{name}}"
        namespace: monitoring
