apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: app-0
        name: gke_kentaiso-330205_asia-northeast1_prod-app-0
      - cluster: corp-0
        name: gke_kentaiso-330205_asia-northeast1_prod-corp-0
      - cluster: misc-0
        name: gke_kentaiso-330205_asia-northeast1_prod-misc-0
  template:
    metadata:
      name: "{{cluster}}-kube-state-metrics"
    spec:
      project: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
      source:
        chart: kube-state-metrics
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 5.6.0
        helm:
          releaseName: "{{cluster}}-kube-state-metrics"
          values: |
      destination:
        name: "{{name}}"
        namespace: monitoring
