apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: little-quest-realtime
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: realtime=asia-northeast1-docker.pkg.dev/kentaiso-330205/little-quest/little-quest-realtime,frontend=asia-northeast1-docker.pkg.dev/kentaiso-330205/little-quest/little-quest-frontend,mmf=asia-northeast1-docker.pkg.dev/kentaiso-330205/little-quest/little-quest-mmf,director=asia-northeast1-docker.pkg.dev/kentaiso-330205/little-quest/little-quest-director
    argocd-image-updater.argoproj.io/realtime.update-strategy: newest-build
    argocd-image-updater.argoproj.io/realtime.ignore-tags: latest
    argocd-image-updater.argoproj.io/realtime.force-update: "true"
    argocd-image-updater.argoproj.io/realtime.helm.image-name: realtime.image.repository
    argocd-image-updater.argoproj.io/realtime.helm.image-tag: realtime.image.tag
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.ignore-tags: latest
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag
    argocd-image-updater.argoproj.io/mmf.update-strategy: newest-build
    argocd-image-updater.argoproj.io/mmf.ignore-tags: latest
    argocd-image-updater.argoproj.io/mmf.force-update: "true"
    argocd-image-updater.argoproj.io/mmf.helm.image-name: mmf.image.repository
    argocd-image-updater.argoproj.io/mmf.helm.image-tag: mmf.image.tag
    argocd-image-updater.argoproj.io/director.update-strategy: newest-build
    argocd-image-updater.argoproj.io/director.ignore-tags: latest
    argocd-image-updater.argoproj.io/director.force-update: "true"
    argocd-image-updater.argoproj.io/director.helm.image-name: director.image.repository
    argocd-image-updater.argoproj.io/director.helm.image-tag: director.image.tag
    notifications.argoproj.io/subscribe.on-sync-succeeded.googlechat: spaceName
spec:
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: asia-northeast1-docker.pkg.dev/kentaiso-330205/little-quest/charts
    chart: little-quest-realtime
    targetRevision: 0.4.3
    helm:
      releaseName: "little-quest-realtime"
      values: |
        realtime:
          serviceName: little-quest-realtime

          image:
            repository: asia-northeast1-docker.pkg.dev/kentaiso-330205/little-quest/little-quest-realtime
            pullPolicy: IfNotPresent
            # Overrides the image tag whose default is the chart appVersion.
            tag: ""

          imagePullSecrets: []
          nameOverride: ""
          fullnameOverride: ""

          serviceAccount:
            # Specifies whether a service account should be created
            create: true
            # Annotations to add to the service account
            annotations:
              iam.gke.io/gcp-service-account: little-quest-realtime@kentaiso-330205.iam.gserviceaccount.com
            # The name of the service account to use.
            # If not set and create is true, a name is generated using the fullname template
            name: ""

          podAnnotations: {}

          scheduling: Packed

          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 25%
              maxUnavailable: 1%

          port:
            # Pod's containerPort
            containerPort: 7654
            portPolicy: Dynamic
            protocol: TCP
            passthrough: "FALSE"
            # HTTP Prometheus metrics port
            metricsPort: "18080"

          health:
            disabled: false
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 3

          sdkServer:
            logLevel: Info
            grpcPort: 9357
            httpPort: 9358

          podSecurityContext: {}
            # fsGroup: 2000

          securityContext: {}
            # capabilities:
            #   drop:
            #   - ALL
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            # runAsUser: 1000

            #liveness:
            #  httpGet:
            #    path: /healthz
            #    port: http
            #  periodSeconds: 10
            #  successThreshold: 1
            #  failureThreshold: 5
            #  timeoutSeconds: 10

            #readiness:
            #  httpGet:
            #    path: /readiness
            #    port: http
            #  periodSeconds: 10
            #  successThreshold: 1
            #  failureThreshold: 5
            #  timeoutSeconds: 10

          startup: {}

          resources:
            # We usually recommend not to specify default resources and to leave this as a conscious
            # choice for the user. This also increases chances charts run on environments with little
            # resources, such as Minikube. If you do want to specify resources, uncomment the following
            # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: '1'
              memory: 128Mi

          nodeSelector:
            app: agones-gameserver

          tolerations:
          - key: "app"
            operator: "Equal"
            value: "agones-gameserver"
            effect: "NoSchedule"

          affinity: {}

          terminationGracePeriodSeconds: 60

          ## Additional volumeMounts
          volumeMounts: {}

          ## Additional Volumes
          volumes: {}

          maxUnavailable: 1

          service:
            annotations: {}
            type: ClusterIP
            port: 80

          autoscaling:
            enabled: true
            type: Buffer
            bufferSize: 4
            minReplicas: 4
            maxReplicas: 100

        frontend:
          serviceName: little-quest-frontend

          image:
            repository: asia-northeast1-docker.pkg.dev/test-project/little-quest/little-quest-frontend
            pullPolicy: IfNotPresent
            # Overrides the image tag whose default is the chart appVersion.
            tag: ""

          imagePullSecrets: []
          nameOverride: ""
          fullnameOverride: ""

          lifecycle:
            preStop:
              exec:
                command:
                - /usr/local/bin/sleep
                - "5"

          serviceAccount:
            # Specifies whether a service account should be created
            create: true
            # Annotations to add to the service account
            annotations:
              iam.gke.io/gcp-service-account: little-quest-frontend@kentaiso-330205.iam.gserviceaccount.com
            # The name of the service account to use.
            # If not set and create is true, a name is generated using the fullname template
            name: ""

          podAnnotations: {}

          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 25%
              maxUnavailable: 0%

          port:
            # Pod's containerPort
            containerPort: 18080

          podSecurityContext: {}
            # fsGroup: 2000

          securityContext: {}
            # capabilities:
            #   drop:
            #   - ALL
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            # runAsUser: 1000

          liveness:
            httpGet:
              path: /healthz
              port: 18080
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10

          readiness:
            httpGet:
              path: /readiness
              port: 18080
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10

          startup: {}

          resources:
            # We usually recommend not to specify default resources and to leave this as a conscious
            # choice for the user. This also increases chances charts run on environments with little
            # resources, such as Minikube. If you do want to specify resources, uncomment the following
            # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: '1'
              memory: 1Gi

          nodeSelector:
            app: agones-gameserver

          tolerations:
          - key: "app"
            operator: "Equal"
            value: "agones-gameserver"
            effect: "NoSchedule"

          affinity: {}

          terminationGracePeriodSeconds: 30

          ## Additional volumeMounts
          volumeMounts: {}

          ## Additional Volumes
          volumes: {}

          maxUnavailable: 1

          service:
            annotations: {}
            type: ClusterIP
            headless: true
            port: 80

          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 100
            targetCPUType: Utilization
            targetCPUUtilizationPercentage: 70
            targetMemoryType: Utilization
            targetMemoryUtilizationPercentage: 70
            targetContainerCPUType: Utilization
            targetContainerCPUUtilizationPercentage: 70

          openMatch:
            frontendService:
              address: open-match-frontend.open-match.svc.cluster.local.:50504

          # Frontend Trace sampling rate
          trace:
            exporter: opentelemetry_collector
            endpoint: opentelemetry-collector.tracing.svc.cluster.local.:4317
            samplingRate: 1.0

        mmf:
          serviceName: little-quest-mmf

          image:
            repository: asia-northeast1-docker.pkg.dev/kentaiso-330205/little-quest/little-quest-mmf
            pullPolicy: IfNotPresent
            # Overrides the image tag whose default is the chart appVersion.
            tag: ""

          imagePullSecrets: []
          nameOverride: ""
          fullnameOverride: ""

          lifecycle:
            preStop:
              exec:
                command:
                - /usr/local/bin/sleep
                - "5"

          serviceAccount:
            # Specifies whether a service account should be created
            create: true
            # Annotations to add to the service account
            annotations:
              iam.gke.io/gcp-service-account: little-quest-mmf@kentaiso-330205.iam.gserviceaccount.com
            # The name of the service account to use.
            # If not set and create is true, a name is generated using the fullname template
            name: ""

          podAnnotations: {}

          replicaCount: 2

          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 25%
              maxUnavailable: 0%

          port:
            # Pod's containerPort
            containerPort: 50502
            # HTTP Prometheus metrics port
            metricsPort: 18080

          podSecurityContext: {}
            # fsGroup: 2000

          securityContext: {}
            # capabilities:
            #   drop:
            #   - ALL
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            # runAsUser: 1000

          liveness:
            grpc:
              port: 50502
              service: matchfunction
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10

          readiness:
            grpc:
              port: 50502
              service: matchfunction
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10

          startup: {}

          resources:
            # We usually recommend not to specify default resources and to leave this as a conscious
            # choice for the user. This also increases chances charts run on environments with little
            # resources, such as Minikube. If you do want to specify resources, uncomment the following
            # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: '1'
              memory: 128Mi

          nodeSelector:
            app: agones-gameserver

          tolerations:
          - key: "app"
            operator: "Equal"
            value: "agones-gameserver"
            effect: "NoSchedule"

          affinity: {}

          terminationGracePeriodSeconds: 30

          ## Additional volumeMounts
          volumeMounts: {}

          ## Additional Volumes
          volumes: {}

          maxUnavailable: 1

          service:
            annotations: {}
            type: ClusterIP
            headless: true
            port: 50502

          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 100
            targetCPUType: Utilization
            targetCPUUtilizationPercentage: 70
            # targetMemoryType: Utilization
            # targetMemoryUtilizationPercentage: 70
            targetContainerCPUType: Utilization
            targetContainerCPUUtilizationPercentage: 70

          openMatch:
            queryService:
              address: open-match-query.open-match.svc.cluster.local.:50503
            playerPerMatch: 4

          # MMF Trace sampling rate
          trace:
            exporter: opentelemetry_collector
            endpoint: opentelemetry-collector.tracing.svc.cluster.local.:4317
            samplingRate: 1.0

        director:
          serviceName: little-quest-director

          image:
            repository: asia-northeast1-docker.pkg.dev/kentaiso-330205/little-quest/little-quest-director
            pullPolicy: IfNotPresent
            # Overrides the image tag whose default is the chart appVersion.
            tag: ""

          imagePullSecrets: []
          nameOverride: ""
          fullnameOverride: ""

          lifecycle:
            preStop:
              exec:
                command:
                - /usr/local/bin/sleep
                - "5"

          serviceAccount:
            # Specifies whether a service account should be created
            create: true
            # Annotations to add to the service account
            annotations:
              iam.gke.io/gcp-service-account: little-quest-director@kentaiso-330205.iam.gserviceaccount.com
            # The name of the service account to use.
            # If not set and create is true, a name is generated using the fullname template
            name: ""

          podAnnotations: {}

          replicaCount: 1

          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 25%
              maxUnavailable: 0%

          port:
            # HTTP Prometheus metrics port
            metricsPort: 18080

          podSecurityContext: {}
            # fsGroup: 2000

          securityContext: {}
            # capabilities:
            #   drop:
            #   - ALL
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            # runAsUser: 1000

          liveness:
            httpGet:
              path: /healthz
              port: 18080
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10

          readiness:
            httpGet:
              path: /readiness
              port: 18080
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10

          startup: {}

          resources:
            # We usually recommend not to specify default resources and to leave this as a conscious
            # choice for the user. This also increases chances charts run on environments with little
            # resources, such as Minikube. If you do want to specify resources, uncomment the following
            # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: '1'
              memory: 128Mi

          nodeSelector:
            app: agones-gameserver

          tolerations:
          - key: "app"
            operator: "Equal"
            value: "agones-gameserver"
            effect: "NoSchedule"

          affinity: {}

          terminationGracePeriodSeconds: 30

          ## Additional volumeMounts
          volumeMounts: {}

          ## Additional Volumes
          volumes: {}

          maxUnavailable: 1

          service:
            annotations: {}
            type: ClusterIP
            port: 80

          autoscaling:
            enabled: false

          openMatch:
            backendService:
              address: open-match-backend.open-match.svc.cluster.local.:50505
            matchFunction:
              host: little-quest-mmf.corp-0.svc.cluster.local.
              port: 50502
            director:
              runInterval: 1s

          agones:
            allocator:
              address: agones-allocator.agones-system.svc.cluster.local.:8443

          # Director Trace sampling rate
          trace:
            exporter: opentelemetry_collector
            endpoint: opentelemetry-collector.tracing.svc.cluster.local.:4317
            samplingRate: 1.0

        # environment(e.g. development, staging, production)
        env: production

        # Google Cloud ProjectId
        googleCloudProjectId: kentaiso-330205

  ignoreDifferences:
  - group: agones.dev
    kind: Fleet
    name: little-quest-realtime
    namespace: corp-0
    jsonPointers:
    - /spec/replicas

  destination:
    name: "gke_kentaiso-330205_asia-northeast1_prod-corp-0"
    namespace: corp-0
