apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-exporter
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: app-0
        name: gke_kentaiso-330205_asia-northeast1_prod-app-0
      - cluster: corp-0
        name: gke_kentaiso-330205_asia-northeast1_prod-corp-0
      - cluster: misc-0
        name: gke_kentaiso-330205_asia-northeast1-a_prod-misc-0
  template:
    metadata:
      name: "{{cluster}}-node-exporter"
    spec:
      project: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      source:
        chart: prometheus-node-exporter
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 4.24.0
        helm:
          releaseName: "{{cluster}}"
      destination:
        name: "{{name}}"
        namespace: monitoring
