apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-exporter
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: app-0
        name: gke_kentaiso-330205_asia-northeast1_prod-app-0
      - cluster: app-1
        name: gke_kentaiso-330205_us-central1_prod-app-1
      - cluster: corp-0
        name: gke_kentaiso-330205_asia-northeast1_prod-corp-0
      - cluster: misc-0
        name: gke_kentaiso-330205_asia-northeast1-a_prod-misc-0
  template:
    metadata:
      name: "{{cluster}}-node-exporter"
    spec:
      project: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      source:
        chart: prometheus-node-exporter
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 4.39.0
        helm:
          releaseName: "{{cluster}}"
          values: |
            extraArgs:
            - --log.format=json
            - --collector.disable-defaults
            - --collector.cpu
            - --collector.conntrack
            - --collector.diskstats
            - --collector.filefd
            - --collector.filesystem
            - --collector.loadavg
            - --collector.meminfo
            - --collector.netdev
            - --collector.stat
            - --collector.vmstat
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                cpu: 100m
                memory: 50Mi
      destination:
        name: "{{name}}"
        namespace: monitoring
