apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: open-match
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: corp-0
        name: gke_kentaiso-330205_asia-northeast1_prod-corp-0
  template:
    metadata:
      name: "open-match"
    spec:
      project: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: asia-northeast1-docker.pkg.dev/kentaiso-330205/open-match/charts
        chart: open-match
        targetRevision: 1.8.1
        helm:
          releaseName: "open-match"
          values: |
             query:
               podAnnotations:
                 proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true, "drainDuration": "20s", "parentShutdownDuration": "30s", "proxyMetadata": {"MINIMUM_DRAIN_DURATION": "20s", "EXIT_ON_ZERO_ACTIVE_CONNECTIONS": "true"}}'
                 sidecar.istio.io/rewriteAppHTTPProbers: "false"
               podLabels:
                 service.istio.io/canonical-name: open-match-query
             frontend:
               podAnnotations:
                 proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true, "drainDuration": "20s", "parentShutdownDuration": "30s", "proxyMetadata": {"MINIMUM_DRAIN_DURATION": "20s", "EXIT_ON_ZERO_ACTIVE_CONNECTIONS": "true"}}'
                 sidecar.istio.io/rewriteAppHTTPProbers: "false"
               podLabels:
                 service.istio.io/canonical-name: open-match-frontend
             backend:
               podAnnotations:
                 proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true, "drainDuration": "20s", "parentShutdownDuration": "30s", "proxyMetadata": {"MINIMUM_DRAIN_DURATION": "20s", "EXIT_ON_ZERO_ACTIVE_CONNECTIONS": "true"}}'
                 sidecar.istio.io/rewriteAppHTTPProbers: "false"
               podLabels:
                 service.istio.io/canonical-name: open-match-backend
             synchronizer:
               podAnnotations:
                 proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true, "drainDuration": "20s", "parentShutdownDuration": "30s", "proxyMetadata": {"MINIMUM_DRAIN_DURATION": "20s", "EXIT_ON_ZERO_ACTIVE_CONNECTIONS": "true"}}'
                 sidecar.istio.io/rewriteAppHTTPProbers: "false"
               podLabels:
                 service.istio.io/canonical-name: open-match-synchronizer
             function: &function
               grpcPort: 50502
               httpPort: 51502

             initContainers:
             - name: sleep
               image: busybox:1.36-musl
               command:
               - cp
               args:
               - /bin/sleep
               - /test/sleep
               volumeMounts:
               - name: test
                 mountPath: /test

             extraVolumeMounts:
             - name: test
               mountPath: /test

             extraVolumes:
             - name: test
               emptyDir: {}

             lifecycleHooks:
               preStop:
                 exec:
                   command:
                   - /test/sleep
                   - "25"

             redis:
               configmap: |
                 maxclients 100000
                 maxmemory 500000000
               master:
                 podAnnotations:
                   sidecar.istio.io/inject: "false"
                 resources:
                   requests:
                     memory: 1Gi
                     cpu: '1'
                   limits:
                     memory: 3Gi
                     cpu: '1'
                 nodeSelector:
                   app: open-match
                 tolerations:
                 - key: "app"
                   operator: "Equal"
                   value: "open-match"
                   effect: "NoSchedule" 

             open-match-core:
               swaggerui:
                 enabled: false

               # Length of time between first fetch matches call, and when no further fetch
               # matches calls will join the current evaluation/synchronization cycle,
               # instead waiting for the next cycle.
               registrationInterval: 250ms
               # Length of time after match function as started before it will be canceled,
               # and evaluator call input is EOF.
               proposalCollectionInterval: 20s
               # Time after a ticket has been returned from fetch matches (marked as pending)
               # before it automatically becomes active again and will be returned by query
               # calls.
               pendingReleaseTimeout: 1m
               # Time after a ticket has been assigned before it is automatically delted.
               assignedDeleteTimeout: 10m
               # Maximum number of tickets to return on a single QueryTicketsResponse.
               queryPageSize: 10000
               # Duration for redis locks to expire.
               backfillLockTimeout: 1m

             open-match-customize:
               enabled: true
               evaluator:
                 enabled: true
                 podAnnotations:
                   proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true, "drainDuration": "20s", "parentShutdownDuration": "30s", "proxyMetadata": {"MINIMUM_DRAIN_DURATION": "20s", "EXIT_ON_ZERO_ACTIVE_CONNECTIONS": "true"}}'
                   sidecar.istio.io/rewriteAppHTTPProbers: "false"
                 podLabels:
                   service.istio.io/canonical-name: open-match-evaluator
                 initContainers:
                 - name: sleep
                   image: busybox:1.36-musl
                   command:
                   - cp
                   args:
                   - /bin/sleep
                   - /test/sleep
                   volumeMounts:
                   - name: test
                     mountPath: /test

                 extraVolumeMounts:
                 - name: test
                   mountPath: /test

                 extraVolumes:
                 - name: test
                   emptyDir: {}

                 lifecycleHooks:
                   preStop:
                     exec:
                       command:
                       - /test/sleep
                       - "25"

               function: *function
               # You can override the evaluator/mmf image
               # evaluator:
               #   image: [YOUR_EVALUATOR_IMAGE]
               # function:
               #   image: [YOUR_MMF_IMAGE]

             open-match-override:
               enabled: true

             global:
               kubernetes:
                 nodeSelector:
                   app: open-match
                 tolerations:
                 - key: "app"
                   operator: "Equal"
                   value: "open-match"
                   effect: "NoSchedule" 
                 horizontalPodAutoScaler:
                   frontend:
                     minReplicas: 2
                     maxReplicas: 20
                     targetCPUUtilizationPercentage: 50
                     targetMemoryUtilizationPercentage: 50
                   backend:
                     minReplicas: 2
                     maxReplicas: 20
                     targetCPUUtilizationPercentage: 50
                     targetMemoryUtilizationPercentage: 50
                   query:
                     minReplicas: 2
                     maxReplicas: 20
                     targetCPUUtilizationPercentage: 50
                     targetMemoryUtilizationPercentage: 50
                   evaluator:
                     minReplicas: 2
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 50
                     targetMemoryUtilizationPercentage: 50
                 resources:
                   requests:
                     memory: 100Mi
                     cpu: 100m
                   limits:
                     memory: 1Gi
                     cpu: '1'
                 serviceAccount: open-match-service
                 serviceAccountAnnotations:
                   iam.gke.io/gcp-service-account: open-match-service@kentaiso-330205.iam.gserviceaccount.com

               gcpProjectId: "kentaiso-330205"

               logging:
                 level: info

               image:
                 registry: asia-northeast1-docker.pkg.dev/kentaiso-330205/open-match
                 tag: 1.8.1-a039dbc
                 pullPolicy: Always
             
               telemetry:
                 reportingPeriod: "1m"
                 traceSamplingFraction: 0.0
                 zpages:
                   enabled: false
                 prometheus:
                   enabled: true
                   endpoint: "/metrics"
                   serviceDiscovery: true
                 stackdriverMetrics:
                   enabled: false
                   prefix: "open_match"

      ignoreDifferences:
      - group: apps
        kind: Deployment
        name: open-match-backend
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: Deployment
        name: open-match-evaluator
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: Deployment
        name: open-match-frontend
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: Deployment
        name: open-match-query
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      destination:
        name: "{{name}}"
        namespace: open-match
