apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: open-match
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: corp-0
        name: gke_kentaiso-330205_asia-northeast1_prod-corp-0
  template:
    metadata:
      name: "open-match"
    spec:
      project: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        automated:
          prune: true
          selfHeal: true
      source:
        chart: open-match
        repoURL: https://open-match.dev/chart/stable
        targetRevision: v1.8.1
        helm:
          releaseName: "open-match"
          values: |
             function: &function
               hostName:
               grpcPort: 50502
               httpPort: 51502
               replicas: 3

             redis:
               master:
                 resources:
                   requests:
                     memory: 300Mi
                     cpu: 100m
                   limits:
                     memory: 6Gi
                     cpu: 6
                 nodeSelector:
                   app: open-match
                 tolerations:
                 - key: "app"
                   operator: "Equal"
                   value: "open-match"
                   effect: "NoSchedule" 
             
             open-match-customize:
               enabled: true
               evaluator:
                 enabled: true
               function: *function
               # You can override the evaluator/mmf image
               # evaluator:
               #   image: [YOUR_EVALUATOR_IMAGE]
               # function:
               #   image: [YOUR_MMF_IMAGE]

             open-match-override:
               enabled: true

             global:
               kubernetes:
                 nodeSelector:
                   app: open-match
                 tolerations:
                 - key: "app"
                   operator: "Equal"
                   value: "open-match"
                   effect: "NoSchedule" 
                 horizontalPodAutoScaler:
                   frontend:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                   backend:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                   query:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                   evaluator:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                   matchfunction:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                 resources:
                   requests:
                     memory: 100Mi
                     cpu: 100m
                   limits:
                     memory: 100Mi
                     cpu: 100m
                 serviceAccount: open-match-service
                 serviceAccountAnnotations:
                   iam.gke.io/gcp-service-account: open-match-service@kentaiso-330205.iam.gserviceaccount.com

               gcpProjectId: "kentaiso-330205"

               logging:
                 level: info
             
               image:
                 registry: asia-northeast1-docker.pkg.dev/kentaiso-330205/open-match
                 tag: 1.8.1-189b5a2
                 pullPolicy: Always
             
               telemetry:
                 reportingPeriod: "1m"
                 traceSamplingFraction: 0.0
                 zpages:
                   enabled: false
                 prometheus:
                   enabled: true
                   endpoint: "/metrics"
                   serviceDiscovery: true
                 stackdriverMetrics:
                   enabled: false
                   prefix: "open_match"

      ignoreDifferences:
      - group: apps
        kind: Deployment
        name: open-match-backend
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: Deployment
        name: open-match-evaluator
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: Deployment
        name: open-match-frontend
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: Deployment
        name: open-match-query
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      destination:
        name: "{{name}}"
        namespace: open-match
