apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: open-match
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: corp-0
        name: gke_kentaiso-330205_asia-northeast1_corp-0
  template:
    metadata:
      name: "open-match"
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      source:
        chart: open-match
        repoURL: https://open-match.dev/chart/stable
        targetRevision: v1.7.0
        helm:
          releaseName: "open-match"
          values: |
             swaggerui: &swaggerui
               hostName:
               httpPort: 51500
               portType: ClusterIP
               replicas: 1
               image: openmatch-swaggerui
             query: &query
               hostName:
               grpcPort: 50503
               httpPort: 51503
               portType: ClusterIP
               replicas: 3
               image: openmatch-query
             frontend: &frontend
               hostName:
               grpcPort: 50504
               httpPort: 51504
               portType: ClusterIP
               replicas: 3
               image: openmatch-frontend
             backend: &backend
               hostName:
               grpcPort: 50505
               httpPort: 51505
               portType: ClusterIP
               replicas: 3
               image: openmatch-backend
             synchronizer: &synchronizer
               hostName:
               grpcPort: 50506
               httpPort: 51506
               portType: ClusterIP
               replicas: 1
               image: openmatch-synchronizer
             evaluator: &evaluator
               hostName:
               grpcPort: 50508
               httpPort: 51508
               replicas: 3
             function: &function
               hostName:
               grpcPort: 50502
               httpPort: 51502
               replicas: 3
             
             # Specifies the location and name of the Open Match application-level config volumes.
             # Used in template: `openmatch.volumemounts.configs` and `openmatch.volumes.configs` under `templates/_helpers.tpl` file.
             configs:
               default:
                 volumeName: om-config-volume-default
                 mountPath: /app/config/default
                 # This will be parsed through the `tpl` function.
                 configName: '{{ include "openmatch.configmap.default" . }}'
               override:
                 volumeName: om-config-volume-override
                 mountPath: /app/config/override
                 # This will be parsed through the `tpl` function.
                 configName: '{{ include "openmatch.configmap.override" . }}'
             
             # Override Redis settings
             # https://hub.helm.sh/charts/stable/redis
             # https://github.com/helm/charts/tree/master/stable/redis
             redis:
               redisPort: 6379
               auth:
                 enabled: false
                 sentinel: false
                 usePasswordFiles: false
               secretMountPath: /opt/bitnami/redis/secrets
               configmap: |
                 maxclients 100000
                 maxmemory 500000000
               sentinel:
                 enabled: true
                 masterSet: om-redis-master
                 port: 26379
               master:
                 disableCommands: [] # don't disable 'FLUSH-' commands
                 resources:
                   requests:
                     memory: 300Mi
                     cpu: 100m
                   limits:
                     memory: 6Gi
                     cpu: 6
                 persistence:
                   enabled: false
                 nodeSelector:
                   app: open-match
                 tolerations:
                 - key: "app"
                   operator: "Equal"
                   value: "open-match"
                   effect: "NoSchedule" 
               metrics:
                 enabled: true
               serviceAccount:
                 create: true
               replica:
                 disableCommands: [] # don't disable 'FLUSH-' commands
                 replicaCount: 1
                 persistence:
                   enabled: false
                 resources:
                   requests:
                     memory: 300Mi
                     cpu: 100m
                   limits:
                     memory: 2Gi
                     cpu: 2
                 nodeSelector:
                   app: open-match
                 tolerations:
                 - key: "app"
                   operator: "Equal"
                   value: "open-match"
                   effect: "NoSchedule"
               sysctlImage:
                 # Enable this setting in production if you are running Open Match under Linux environment
                 enabled: true
                 mountHostSys: true
                 # Redis may require some changes in the kernel of the host machine to work as expected,
                 # in particular increasing the somaxconn value and disabling transparent huge pages.
                 # https://github.com/helm/charts/tree/master/stable/redis#host-kernel-settings
                 command:
                   - /bin/sh
                   - -c
                   - |-
                     echo never > /host-sys/kernel/mm/transparent_hugepage/enabled # Disable THP support
                     install_packages procps
                     sysctl -w net.core.somaxconn=100000
             ###############################################################################################################################
             #                               Open Match configurations for the subcharts
             #
             # Open Match uses subcharts to control its `functional granularity`.
             # You are able to override configurations in a subchart by having a key-value pair under its corresponding subchart section.
             #
             # 1. open-match-telemetry: Kubernetes definitions of the integrated monitoring tools along with the core Open Match componenets.
             # 2. open-match-customize: Kubernetes definitions of the customizable template to use Open Match with your own MMFs and Evaluator.
             ###############################################################################################################################
             
             # Controls if users need to install backend, frontend, query, om-configmap, and swaggerui.
             open-match-core:
               enabled: true
             
               # Length of time between first fetch matches call, and when no further fetch
               # matches calls will join the current evaluation/synchronization cycle,
               # instead waiting for the next cycle.
               registrationInterval: 250ms
               # Length of time after match function as started before it will be canceled,
               # and evaluator call input is EOF.
               proposalCollectionInterval: 20s
               # Time after a ticket has been returned from fetch matches (marked as pending)
               # before it automatically becomes active again and will be returned by query
               # calls.
               pendingReleaseTimeout: 1m
               # Time after a ticket has been assigned before it is automatically delted.
               assignedDeleteTimeout: 10m
               # Maximum number of tickets to return on a single QueryTicketsResponse.
               queryPageSize: 10000
               # Duration for redis locks to expire.
               backfillLockTimeout: 1m
             
               redis:
                 enabled: true
                 # If open-match-core.redis.enabled is set to false, have Open Match components talk to this redis address instead.
                 # Otherwise the default is set to the om-redis instance.
                 hostname: # Your redis server address
                 port: 6379
                 user:
                 pool:
                   maxIdle: 500
                   maxActive: 500
                   idleTimeout: 0
                   healthCheckTimeout: 300ms
               swaggerui:
                 enabled: false
             
             # Controls if users need to install scale testing setup for Open Match.
             open-match-scale:
               # Switch the value between true/false to turn on/off this subchart
               enabled: false
             
             # Controls if users need to install the monitoring tools in Open Match.
             open-match-telemetry:
               # Switch the value between true/false to turn on/off this subchart
               enabled: false
             
             # Controls if users need to install their own MMFs and Evaluator in Open Match.
             open-match-customize:
               # Switch the value between true/false to turn on/off this subchart
               enabled: true
               evaluator:
                 enabled: true
               function: *function
               # You can override the evaluator/mmf image
               # evaluator:
               #   image: [YOUR_EVALUATOR_IMAGE]
               # function:
               #   image: [YOUR_MMF_IMAGE]

             open-match-override:
               enabled: true

             # Global configurations that are visible to all subcharts
             global:
               kubernetes:
                 # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
                 nodeSelector:
                   app: open-match
                 # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
                 tolerations:
                 - key: "app"
                   operator: "Equal"
                   value: "open-match"
                   effect: "NoSchedule" 
                 # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
                 affinity: {}
                 horizontalPodAutoScaler:
                   frontend:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                   backend:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                   query:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                   evaluator:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                   matchfunction:
                     minReplicas: 1
                     maxReplicas: 10
                     targetCPUUtilizationPercentage: 60
                 resources:
                   requests:
                     memory: 100Mi
                     cpu: 100m
                   limits:
                     memory: 100Mi
                     cpu: 100m
                 # Overrides the name of the service account which provides an identity for processes that run in a Pod in Open Match.
                 serviceAccount:
                 # Use this field if you need to override the port type for all services defined in this chart
                 service:
                   portType:

               gcpProjectId: "kentaiso-330205"
             
               # Defines if Open Match needs to serve secure traffic
               tls:
                 enabled: false
                 server:
                   mountPath: /app/secrets/tls/server
                 rootca:
                   mountPath: /app/secrets/tls/rootca
             
               logging:
                 rpc:
                   enabled: false
             
               # Use this field if you need to override the image registry and image tag for all services defined in this chart
               image:
                 registry: gcr.io/open-match-public-images
                 tag: 1.7.0
                 pullPolicy: Always
             
               # Expose the telemetry configurations to all subcharts because prometheus, for example,
               # requires pod-level annotation to customize its scrape path.
               # See definitions in templates/_helpers.tpl - "prometheus.annotations" section for details
               telemetry:
                 reportingPeriod: "1m"
                 traceSamplingFraction: 0.005 # What fraction of traces to sample.
                 zpages:
                   enabled: true
                 jaeger:
                   enabled: false
                   agentEndpoint: '{{ include "openmatch.jaeger.agent" . }}'
                   collectorEndpoint: '{{ include "openmatch.jaeger.collector" . }}'
                 prometheus:
                   enabled: true
                   endpoint: "/metrics"
                   serviceDiscovery: true
                 stackdriverMetrics:
                   enabled: true
                   prefix: "open_match"
                 grafana:
                   enabled: false
      ignoreDifferences:
      - group: apps
        kind: Deployment
        name: open-match-backend
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: Deployment
        name: open-match-evaluator
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: Deployment
        name: open-match-frontend
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      - group: apps
        kind: Deployment
        name: open-match-query
        namespace: open-match
        jsonPointers:
        - /spec/replicas
      destination:
        name: "{{name}}"
        namespace: open-match
