{{- if .Values.multiClusterGateway.enabled }}
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "little-quest.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "little-quest.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "little-quest.annotations" . | nindent 4 }}
  {{- end }}
spec:
  {{- range .Values.multiClusterGateway.httpRoute.hosts }}
  hostnames:
  - {{ . | quote }}
  {{- end }}
  parentRefs:
  - kind: Gateway
    name: {{ include "little-quest.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
  rules:
  - matches:
      {{- toYaml .Values.multiClusterGateway.httpRoute.path | nindent 4 }}
    backendRefs:
      {{- toYaml .Values.multiClusterGateway.httpRoute.backendRef | nindent 4 }}
{{- end }}
