apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "little-quest.fullname" . }}-config 
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "little-quest.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "little-quest.annotations" . | nindent 4 }}
  {{- end }}
data:
