{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "little-quest.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "little-quest.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "little-quest.annotations" . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "little-quest.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: {{ .Values.autoscaling.targetCPUType }}
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: {{ .Values.autoscaling.targetMemoryType }}
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.targetContainerCPUUtilizationPercentage }}
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ .Chart.Name }}
      target:
        type: {{ .Values.autoscaling.targetContainerCPUType }}
        averageUtilization: {{ .Values.autoscaling.targetContainerCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
