apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "little-quest.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "little-quest.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "little-quest.annotations" . | nindent 4 }}
  {{- end }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "little-quest.selectorLabels" . | nindent 6 }}
