apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "little-quest.fullname" . }}
  labels:
    {{- include "little-quest.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.googleCloudProjectId }}/secrets/mysql_little_quest_user_password/versions/latest"
        path: mysql_password
      - resourceName: "projects/{{ .Values.googleCloudProjectId }}/secrets/redis_password/versions/latest"
        path: redis_password
  secretObjects:
  - type: Opaque
    labels:
      app.kubernetes.io/part-of: argocd
    secretName: middleware-env
    data:
    - key: mysql_password
      objectName: mysql_password
    - key: redis_password
      objectName: redis_password
