apiVersion: v1
kind: Service
metadata:
  name: {{ include "little-quest.fullname" . }}
  labels:
    {{- include "little-quest.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    appProtocol: http
    targetPort: http
  selector:
    {{- include "little-quest.selectorLabels" . | nindent 4 }}
