kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
 name: {{ .Values.serviceExport.namePrefix }}-{{ include "little-quest.fullname" . }}
 namespace: {{ .Release.Namespace | quote }}
 labels:
    {{- include "little-quest.labels" . | nindent 4 }}
 {{- if .Values.commonAnnotations }}
 annotations:
   {{- include "little-quest.annotations" . | nindent 4 }}
 {{- end }}
