ingress:
  managedcertificate:
    enabled: false
  hosts: []

backendConfig:
  enabled: false
  spec:
    healthCheck:
      checkIntervalSec: 30
      timeoutSec: 5
      healthyThreshold: 1
      unhealthyThreshold: 2
      type: HTTP
      requestPath: /healthz
      port: 8080

storageClass:
  enabled: false
  type: pd-standard
  provisioner: kubernetes.io/gce-pd
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowedTopologies:
    enabled: false
    expressions: []
