ingress:
  managedcertificate:
    enabled: false
  hosts: []

backendConfig:
  enabled: false
  spec:
    healthCheck:
      checkIntervalSec: 30
      timeoutSec: 5
      healthyThreshold: 1
      unhealthyThreshold: 2
      type: HTTP
      requestPath: /healthz
      port: 8080
