apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: agones
  namespace: agones-system
spec:
  selector:
    matchLabels:
      app: agones
  endpoints:
  - port: http
    interval: 60s
    metricRelabeling:
    - sourceLabels: [__name__]
      action: drop
      regex: agones_fleet_autoscalers_buffer_size|agones_fleet_autoscalers_desired_replicas_count|agones_gameservers_state_duration|agones_k8s_client_http_request_total|agones_k8s_client_http_request_duration_seconds_bucket|agones_k8s_client_http_request_duration_seconds_count|agones_k8s_client_http_request_duration_seconds_sum|agones_k8s_client_cache_list_total|agones_k8s_client_cache_list_duration_seconds|agones_k8s_client_cache_list_items|agones_k8s_client_cache_watches_total|agones_k8s_client_cache_last_resource_version|agones_k8s_client_workqueue_depth|agones_k8s_client_workqueue_latency_seconds_bucket|agones_k8s_client_workqueue_latency_seconds_count|agones_k8s_client_workqueue_latency_seconds_sum|agones_k8s_client_workqueue_items_total|agones_k8s_client_workqueue_work_duration_seconds_bucket|agones_k8s_client_workqueue_work_duration_seconds_count|agones_k8s_client_workqueue_work_duration_seconds_sum|agones_k8s_client_workqueue_retries_total|agones_k8s_client_workqueue_longest_running_processor|agones_k8s_client_workqueue_unfinished_work_seconds
