apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: little-quest-director
  namespace: corp-0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: little-quest-director
  endpoints:
  - port: http
    interval: 60s
