apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: little-quest-server
  namespace: little-quest-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: little-quest-server
  endpoints:
  - port: http
    interval: 60s
