{{- if .Values.ingress.managedcertificate.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ template "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
{{ include "namespace" . | indent 2 }}
spec:
  domains:
  {{- range .Values.ingress.hosts }}
  - {{ . | quote }}
  {{- end }}
{{ end }}
