{{- if .Values.director.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "little-quest-director.serviceAccountName" . }}
  labels:
    {{- include "little-quest-director.labels" . | nindent 4 }}
  {{- with .Values.director.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
